### ISSUE TITLE
Create Docker file to create the image

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/GoLLM#2]

**Comment by j2whiting** [comment]
This is done. 

Example usage:
```
docker build -t gollm-test .
docker run -e OPENAI_API_KEY=$OPENAI_API_KEY -it gollm-test --input test_data/test_input_model_config.json
```

The app expects a .json with the following fields:

'amr': json string (Petri net model representation, missing config values.)
'research_paper': str (OCR text from a paper)

The CLI app should be replaced with a fastapi endpoint. Also this pipeline is still quite slow clocking in around 2 min. This can be improved.
